Lint_task:
  container:
    image: rust:1.73
  script:
    - cargo clippy

Linux_task:
  alias: Linux tests
  registry_cache:
    folder: $CARGO_HOME/registry
    fingerprint_script: cat Cargo.lock
  target_cache:
    folder: target
    fingerprint_script:
      - rustc --version
      - cat Cargo.lock
  container:
    image: rust:1.73
  install_script:
    - apt update
    - apt install libclang-dev
  cargo_build_script:
    - cargo test --no-run
  script:
    - cargo test
  before_cache_script: rm -rf $CARGO_HOME/registry/index

success_task:
  name: CI success
  container: {image: "busybox"}
  depends_on:
    - Lint
    - Linux tests
