WHITESPACE = _{ " " | "\t" | NEWLINE }
// COMMENT = { '#' ~ .* ~ NEWLINE }

ident = @{ ASCII_ALPHANUMERIC+ }

string = { (!"\"" ~ ANY)+ }
string_with_quotes = _{ "\"" ~ string ~ "\"" }

mode = { "append" | "immediate" }
folder = { "folder" ~ string_with_quotes ~ "(" ~ mode ~ ")" ~ string_with_quotes+ ~ ";"}

digits = @{ ASCII_DIGIT+ }
assignment = { ident ~ "=" ~ (digits | string_with_quotes) }

program = _{ WHITESPACE+ ~ assignment+ ~ folder+ ~ WHITESPACE* }
